#-------------------------- Initial Setup -------------------------------------#
  units             lj
  atom_style        atomic
  boundary          p p p # PBC
#------------------------------------------------------------------------------#


#-------------------------- Atomic Setup --------------------------------------#
# Reads data from thermal simulation and adds pair_coeff's because read data
# does not store these correctly

  pair_style        lj/cut 2.5 # Define interaction potential.
  read_data         data.lowerT

  pair_coeff        1 1 1.0 1.0
  pair_coeff        1 2 1.5 0.80 
  pair_coeff        2 2 0.5 0.88

#------------------------------------------------------------------------------#


#-------------------------------- Dumps ---------------------------------------#
# Dump stride is choosen so that frames are printed every sqrt(\epsilon/\sigma)
# timesteps as in Schoenholz Nature 2016. Subsequent simulations should have 
# higher stride once we do not need to calculate p-hop
  dump              dumpID all custom 200 run.lammpstrj id type x y z
#------------------------------------------------------------------------------#


#------------------------------ Fixes -----------------------------------------#
# Temperature was choosen by looking at Sam's PNAs T=0.47 is above MCT of KA
# model
  fix               integrator all nvt temp 0.47 0.47 1.0
#------------------------------------------------------------------------------#


#------------------------- Thermo stuff ---------------------------------------#
# Timestep chosen so that we are well below (~1/40) the fastest vibrational 
# frequency of the system (sqrt(m/V''(r0)) where r0 is the minima of the LJ
# potential. Thermo choosen for same reason as dump. Initial velocity choosen
# to be temperature of initial randomization
  thermo_style      custom step pe ke press temp # Output.
  thermo            200 # Output stride.
  timestep          0.005
#------------------------------------------------------------------------------#


#------------------------- Running the Simulation -----------------------------#
# Simulation length choosen to be 1x \tau_alpha time. This should give 1000
# frames. 
  run               200000
#------------------------------------------------------------------------------#


#------------------------- Writing Simulation data ----------------------------#
  write_data        data.run
#------------------------------------------------------------------------------#
